#!/bin/bash
#Ver canales de televisión y radio por streaming

#Ruta al archivo de configuración de canales y radios
CANALES="/home/$USER/radio/radio.conf"

#Reproductores disponibles VLC y MPV
#PLAYER="vlc -f --no-loop --play-and-exit"
PLAYER="mpv --fs"

VERSION="3.1.0"

function userChoice() {

    local limite=$1
    local cadena="$2"
    local reply
    let reply=0

    echo > /dev/tty
    echo "$cadena" > /dev/tty
    read reply < /dev/tty
    echo > /dev/tty

#Vemos si el usuario ingresó un número como el que necesitamos
    while [[ "$reply" -lt 0 ]] || [[ "$reply" -gt  $limite ]]; do

#Si se introduce un número erroneo vemos el siguiente mensaje
	echo "Tiene que introducir un número de entre los indicados:" > /dev/tty
	read reply < /dev/tty
	#echo "Reply es: $reply" > /dev/tty

    done

    echo $reply
}

function getURL() {
    local canal="$1"
    
    local url="${canal##*|}"
    url=$(tr -d '\n' <<< "$url")
    echo "$url"
}

function getNombre() {
    local canal="$1"

    local nombre="${canal%|*}"
    echo "$nombre"
}

function checkConfig() {
    if ! [ -f "$CANALES" ]; then
	echo "Es la primera vez que ejecuta el script."
	echo "Se procederá a descargar el archivo de configuración. Este se va a guardar en el directorio /home/usuario/radio:"
	cd /home/$USER/radio 2>&1
	wget -O "$CANALES" https://raw.githubusercontent.com/sapoclay/radio/main/radio.conf 2>&1
    fi
}

echo "TV y Radio version $VERSION - Basado en el script de Julio Serrano"
echo "Ver televisión o escuchar radio de España vía streaming."
echo

checkConfig

readarray canales < "$CANALES"
if [[ ${#CANALES[@]} == 0 ]]; then
    echo "No hay canales!"
    echo
    echo "Por alguna razón no tiene canales en tu fichero de configuración o no tienes archivo de configuración."
    echo
    echo "Asegurate de tener conexión a internet la próxima vez que ejecutes el script."
fi

if [[ "$#" > 0 ]]; then
    cadena=${*,,}
    let i=0
    for canal in "${canales[@]}"; do
    	nombre=$(getNombre "$canal")
    	p="$nombre"
	s=${p,,}
	if [[ $s == *"$cadena"* ]]; then
	    chosen=$i
	    break
	fi
	(( i++ ))
    done

    if [[ $i == ${#canales[@]} ]]; then
	echo "No se ha encontrado ninguna cadena que coincida con \"$@\""
	exit
    fi
else
    let i=0
    echo "Estaciones de televisión y radio"
    echo "--------------------------------"
    for canal in "${canales[@]}"; do
	echo "$i) $(getNombre "$canal")"
	(( i++ ))
    done

    limite=$(( ${#canales[@]} - 1 ))
    chosen=$(userChoice $limite "Selecciona la estación para reproducirla:")
fi

canal=${canales[$chosen]}
nombre=$(getNombre "$canal")
url=$(getURL "$canal")
echo "Has elegido el canal $nombre"

if [ -f /tmp/tvpid ]; then
    tvpid=$(< /tmp/tvpid)
    #echo "tvpid: $tvpid"
    if [[ $tvpid != "" ]]; then 
	pcmd=$(ps -p $tvpid -o comm=)
	#Debug
	#echo "Comando: >$pcmd<"
	if [[ "$pcmd" == "vlc" ]] || [[ "$pcmd" == "mpv" ]]; then
	    echo "Matando el reproductor para cambiar de canal..."
	    kill -9 "$tvpid"
	fi
    fi
fi

echo "Reproduciendo el canal " $nombre
${PLAYER} "$url" 2> /dev/null &
echo "$!" > /tmp/tvpid
